# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in my-folder
      run: |
        # 使用 ls 命令列出 my-folder 中的檔案
        files=$(ls)
        echo "$files" > files-list.txt
        # 或者，將它們輸出為步驟的輸出變數
        echo "::set-output name=files::$files"

    - name: Upload files list
      uses: actions/upload-artifact@v2
      with:
        name: files-list
        path: files-list.txt
