# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-images-urls:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write     
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update imagesUrls.json
      run: |
        mainfolder="images/jpg"
        subfolders=("Nature" "Props" "Scene")
        declare -A imagePaths
        
        for subfolder in "${subfolders[@]}"; do
          subfolderPath="$mainfolder/$subfolder"
          echo "subfolderPath: $subfolderPath"
          if [ -d "$subfolderPath" ]; then
            allFiles=($(ls "$subfolderPath"))
            echo "allFiles: ${allFiles[@]}"
            
            jpgFiles=()
            for file in "${allFiles[@]}"; do
              if [[ "$file" == *.jpg ]]; then
                jpgFiles+=("$file")
              fi
            done
            echo "jpgFiles: ${jpgFiles[@]}"
            
            jpgPaths=()
            for file in "${jpgFiles[@]}"; do
              jpgPaths+=("$subfolderPath/$file")
            done
            echo "jpgPaths: ${jpgPaths[@]}"
            
            imagePaths["$subfolder"]=("${jpgPaths[@]}")
            echo "imagePaths: ${imagePaths[@]}"
          else
            echo "Error reading image files in $subfolder"
          fi
        done
        
        jsonContent=$(declare -p imagePaths)
        echo "$jsonContent" > "imagesUrls.json"

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add imagesUrls.json
        git commit -m "Update imagesUrls.json"
        git push
